spring.application.name=product.review
spring.datasource.url= jdbc:postgresql://ep-cold-water-aymme3dn-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WUZqrJv5mh4g